### PR TITLE
DRCs

### PR DESCRIPTION
**Pull request by Arvind-Srinivasan**
Draft PR that adds DRU files for Seeed Studio, ALLPCB, JLCPCB, EuroCircuits, OshPark, Advanced Circuits, and a standard set of defaults.

### CODE REVIEW

**Review by varunm99 — COMMENTED** [review]
Might want to check the JLC DRC against this one:
https://www.arxterra.com/jlcpcb-drc-generating-gerber-files-and-ordering/
Just for sanity checking

**Review by mmaisonneuve3 — COMMENTED** [review]
I would not even include Seeds and OshPark as we almost never use them

**Review by mmaisonneuve3 — APPROVED** [review]

**Review by mmaisonneuve3 — APPROVED** [review]

**Comment by ashbhan** [comment]
Ran all 2 layer drcs on IGVC Logic Board. Got clearance issues on JLC, ALL, and Seed. Pictures below are with JLC but all three seem to be having errors on the same stuff. Board is [here](https://github.com/RoboJackets/igvc-electrical/tree/rev/logic/core-boards/logic/Eagle%20Files) for reference. 
Screenshot from 2020-06-19 10-23-56
Some vias

Screenshot from 2020-06-19 10-22-26
Traces between mbed header pins

Screenshot from 2020-06-19 10-22-49
Level shifter pads

Screenshot from 2020-06-19 10-27-22
Trace and pad for CAN transceiver

Screenshot from 2020-06-19 10-27-35
Some IC and via issue? 


In general, problem areas seem to be between traces and the mbed header pins, between vias, between pads of parts, and traces and pads. Screenshots taken with a .127 mm grid.

**Comment by ashbhan** [comment]
I don't there's a problem with including Osh or Seed since you have them here already. Might be good to have some sort of readme where we list when we order from each one? Like JLC/ALL for your standard 2 layer not super complicated stuff, euro if you need a high quality board? Idk

**Comment by Arvind-Srinivasan** [comment]
Yea, we could add a table or something to the README that outlines board fab priority?

**Comment by ashbhan** [comment]
Sounds good. Also approximate time it takes for the boards to arrive from date of order would be super useful.

**Review by varunm99 — APPROVED** [review]
cool and good

**Pull request merged**
